apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: argocd-guestbook-environments
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-bf1e57c4-6088-4307-a0c1-c37e44abd746:
      events:
        - push
      repositories:
        - owner: codefresh-contrib
          names:
            - argocd-guestbook-environments
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-salesdemo-dev/argocd-guestbook-environments/github-bf1e57c4-6088-4307-a0c1-c37e44abd746
        url: https://dev.csdp-salesdemo.sa.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
