apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: development-deploy-and-promote
spec:
  entrypoint: deploy-and-promote
  templates:
    - name: deploy-and-promote
      inputs:
        parameters:
          - name: ARGOCD_APP
          - name: ARGOCD_SERVER
            default: argocd-server
          - name: REPO_OWNER
          - name: REPO_URL
          - name: PROMOTION_SOURCE_FILE
          - name: PROMOTION_TARGET_FILE
            default: 'nil'
          - name: TARGET_DEPLOYMENT_BRANCH
            default: 'main'
          - name: TARGET_DEPLOYMENT_REPOSITORY
          - name: SOURCE_DEPLOYMENT_BRANCH
            default: 'main'
          - name: SOURCE_FILE_PATH_PREFIX
          - name: TARGET_FILE_PATH_PREFIX
          - name: GIT_TOKEN_SECRET
            default: 'github-token'
      dag:
        tasks:
          # Deploy Application and Promote Candidate
          - name: deploy-and-promote
            templateRef:
              name: shared-gitops-promotion
              template: deploy-and-promote